// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09MsW7ZUs3svq4C8ofyFCPEAGc04-_Kc',
    appId: '1:1095455799466:web:f4c60fac32acb769cc78d3',
    messagingSenderId: '1095455799466',
    projectId: 'twitter-magdy',
    authDomain: 'twitter-magdy.firebaseapp.com',
    storageBucket: 'twitter-magdy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8fE1P6FJiYgEGw510b8887nSgBKpfBNQ',
    appId: '1:1095455799466:android:a051037f22d31804cc78d3',
    messagingSenderId: '1095455799466',
    projectId: 'twitter-magdy',
    storageBucket: 'twitter-magdy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC981ghUJMSfayn2VTJZxhw6lGmrLRd_BM',
    appId: '1:1095455799466:ios:652e6a154b58b028cc78d3',
    messagingSenderId: '1095455799466',
    projectId: 'twitter-magdy',
    storageBucket: 'twitter-magdy.appspot.com',
    iosBundleId: 'com.example.ztmcourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC981ghUJMSfayn2VTJZxhw6lGmrLRd_BM',
    appId: '1:1095455799466:ios:da68a6b53a0d22facc78d3',
    messagingSenderId: '1095455799466',
    projectId: 'twitter-magdy',
    storageBucket: 'twitter-magdy.appspot.com',
    iosBundleId: 'com.example.ztmcourse.RunnerTests',
  );
}
